package ru.intelinfo.inczilla.mvc.repository;

import java.sql.*;
import java.util.HashMap;
import java.util.Map;

public class CompanyDebtRepository {

    public void initSchema(Connection conn) throws SQLException {
        try (Statement st = conn.createStatement()) {

            st.executeUpdate("""
                create table if not exists tax_type (
                  id smallint generated by default as identity primary key,
                  name varchar(255) not null unique
                )
            """);

            st.executeUpdate("""
                create table if not exists debt (
                  inn bigint not null,
                  tax_type_id smallint not null,
                  amount_kopeks bigint not null,
                  primary key (inn, tax_type_id),
                  foreign key (tax_type_id) references tax_type(id)
                )
            """);
        }
    }

    public void initStageSchema(Connection conn) throws SQLException {
        try (Statement st = conn.createStatement()) {
            // RAW stage без ключей: максимальная скорость вставки
            st.executeUpdate("""
                create table if not exists debt_stage_raw (
                  inn bigint not null,
                  tax_type_id smallint not null,
                  amount_kopeks bigint not null
                )
            """);
        }
    }

    public void clearStage(Connection conn) throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.executeUpdate("truncate table debt_stage_raw");
        }
    }

    public void replaceMainWithStageAggregated(Connection conn) throws SQLException {
        try (Statement st = conn.createStatement()) {
            st.executeUpdate("truncate table debt");

            st.executeUpdate("""
                insert into debt(inn, tax_type_id, amount_kopeks)
                select inn, tax_type_id, sum(amount_kopeks)
                from debt_stage_raw
                group by inn, tax_type_id
            """);
        }
    }

    public short getOrCreateTaxTypeId(Connection conn, String taxName) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("select id from tax_type where name = ?")) {
            ps.setString(1, taxName);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return rs.getShort(1);
            }
        }

        try (PreparedStatement ins = conn.prepareStatement("insert into tax_type(name) values (?)")) {
            ins.setString(1, taxName);
            ins.executeUpdate();
        } catch (SQLException ignore) {
        }

        try (PreparedStatement ps = conn.prepareStatement("select id from tax_type where name = ?")) {
            ps.setString(1, taxName);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) throw new SQLException("tax_type id not found for: " + taxName);
                return rs.getShort(1);
            }
        }
    }

    // Статистика SQL

    public int countCompanies(Connection conn) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("select count(distinct inn) from debt");
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            return rs.getInt(1);
        }
    }

    public long maxTotalDebtPerCompanyKopeks(Connection conn) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("""
            select coalesce(max(total), 0)
            from (
              select inn, sum(amount_kopeks) as total
              from debt
              group by inn
            ) t
        """);
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            return rs.getLong(1);
        }
    }

    public long avgTotalDebtPerCompanyKopeks(Connection conn) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("""
            select coalesce(avg(total), 0)
            from (
              select inn, sum(amount_kopeks) as total
              from debt
              group by inn
            ) t
        """);
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            return rs.getLong(1);
        }
    }

    public Map<String, Long> maxDebtByTaxTypeKopeks(Connection conn) throws SQLException {
        Map<String, Long> result = new HashMap<>();
        try (PreparedStatement ps = conn.prepareStatement("""
            select tt.name, max(d.amount_kopeks)
            from debt d
            join tax_type tt on tt.id = d.tax_type_id
            group by tt.name
        """);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                result.put(rs.getString(1), rs.getLong(2));
            }
        }
        return result;
    }
}